"""message

Revision ID: 1a35675550bc
Revises: fea2acced85d
Create Date: 2023-08-08 20:42:24.742081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a35675550bc'
down_revision = 'fea2acced85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planted_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('planted_on')

    # ### end Alembic commands ###
