"""empty message

Revision ID: eb89ef954451
Revises: c3d49b527d5f
Create Date: 2023-08-10 11:49:59.055012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb89ef954451'
down_revision = 'c3d49b527d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.id'], name=op.f('fk_users_greenhouse_id_greenhouses')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('greenhouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greenhouses', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('users')
    # ### end Alembic commands ###
