"""final server upgrade

Revision ID: 1fc12bd078df
Revises: 7102e36f06af
Create Date: 2023-08-11 11:18:29.599926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc12bd078df'
down_revision = '7102e36f06af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plants_zone_id_zones', type_='foreignkey')
        batch_op.drop_column('zone_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_plants_zone_id_zones', 'zones', ['zone_id'], ['id'])

    # ### end Alembic commands ###
