"""empty message

Revision ID: 96a7bf945c42
Revises: feab25096da0
Create Date: 2023-08-08 09:50:38.202936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a7bf945c42'
down_revision = 'feab25096da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_plant_beds_plant_id_plants')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_plant_beds_zone_id_zones')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sunlight_range', sa.Integer(), nullable=True))
        batch_op.drop_column('humidity_range')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('humidity_range', sa.INTEGER(), nullable=True))
        batch_op.drop_column('sunlight_range')

    op.drop_table('plant_beds')
    # ### end Alembic commands ###
